### ISSUE TITLE
Query error: 1054 Unknown column 'Array' in 'where clause' (ApiStashEdit::checkCache)

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/wiki#4]
On about every second edit of the [annotation health](https://wikiapiary.com/wiki/Semantic_statistics/Annotation_Health page) I get this error message. To save the page I have to do a trivial change between the first and last char of wikitext.

``` text
A database query error has occurred. This may indicate a bug in the software.

    Query:
    SELECT 1 FROM `page` WHERE (Array) OR (Array) OR (Array) LIMIT 1
    Function: ApiStashEdit::checkCache
    Error: 1054 Unknown column 'Array' in 'where clause' (db-local)
```

@thingles I guess it will be nice to have a stack trace for this.

**Comment by kghbln** [comment]
That's a new variant:

``` text
    Query:
    SELECT 1 FROM `page` WHERE (Array) LIMIT 1
    Function: ApiStashEdit::checkCache
    Error: 1054 Unknown column 'Array' in 'where clause' (db-local)
```

**Comment by mwjames** [comment]
[0] give some hints as to what `ApiStashEdit` actually does (apparently you can disable it [1]) and it seems someone made a 1.25 backport [2].

[0] https://phabricator.wikimedia.org/T113189
[1] https://www.mediawiki.org/wiki/Manual:$wgAjaxEditStash
[2] https://gerrit.wikimedia.org/r/#/c/244453/

**Comment by kghbln** [comment]
Thanks a ton for the info! Apparently not backported to the MW 1.25.x branch. One of MW's finest hours?

**Comment by kghbln** [comment]
Ah, no. This was one of my finest moments. The backport was not referenced to the issue and I forgot about [2] the moment I hit save. :(

**Comment by jthingelstad** [comment]
Closing now with upgrade to 1.25.3.
